### ISSUE TITLE
I can't get it to work.

### ISSUE THREAD

**Issue by ghost** [piotr-e/Stk1160-raspberrypi#1]
[  199.149774] usb 1-1.3: USB disconnect, device number 4
[  209.883347] usb 1-1.2: new high-speed USB device number 5 using dwc_otg
[  209.984380] usb 1-1.2: New USB device found, idVendor=05e1, idProduct=0408
[  209.984407] usb 1-1.2: New USB device strings: Mfr=1, Product=2, SerialNumber=0
[  209.984422] usb 1-1.2: Product: USB 2.0 Video Capture Controller
[  209.984434] usb 1-1.2: Manufacturer: Syntek Semiconductor
[  210.063284] stk11xx: disagrees about version of symbol module_layout
[  210.071762] stk11xx: disagrees about version of symbol module_layout
[  210.072283] stk1160: disagrees about version of symbol module_layout
[  210.092595] stk1160: disagrees about version of symbol module_layout
## 

Any advice?
Thanks

**Comment by ezequielgarcia** [comment]
I'm not sure what's going on, perhaps with some more information I'd be happier:

**full** dmesg, lsmod, uname -a, etc. etc.

**Comment by ghost** [comment]
My dmesg is tooo flooded with Shorewall info. I've pasted above the only info dmesg provided me, after connected the easycap.

root@medusa:~# uname -a  
Linux medusa 3.2.27+ #250 PREEMPT Thu Oct 18 19:03:02 BST 2012 armv6l GNU/Linux

root@medusa:~# lsmod
Module                  Size  Used by
cpufreq_stats           2724  0 
fuse                   66685  3 
act_police              4139  0 
cls_basic               3764  0 
cls_flow                6975  0 
cls_fw                  3666  0 
cls_u32                 6471  0 
sch_tbf                 4070  0 
sch_prio                4022  0 
sch_htb                13671  0 
sch_hfsc               14424  0 
sch_sfq                 5710  0 
xt_statistic            1159  0 
xt_CT                   1728  0 
xt_time                 2007  0 
xt_connlimit            3173  0 
xt_realm                 824  0 
xt_addrtype             2505  0 
iptable_raw             1268  0 
xt_comment               782  0 
xt_recent               8877  0 
xt_policy               2500  0 
ipt_ULOG                5630  0 
ipt_REJECT              2071  0 
ipt_REDIRECT            1067  0 
ipt_NETMAP              1015  0 
ipt_MASQUERADE          1605  0 
ipt_ECN                 1703  0 
ipt_ecn                 1319  0 
ipt_ah                   991  0 
xt_set                  4161  0 
ip_set                 24387  1 xt_set
nf_nat_tftp              846  0 
nf_nat_snmp_basic       7519  0 
nf_conntrack_snmp       1407  1 nf_nat_snmp_basic
nf_nat_sip              6232  0 
nf_nat_pptp             2202  0 
nf_nat_proto_gre        1381  1 nf_nat_pptp
nf_nat_irc              1440  0 
nf_nat_h323             5863  0 
nf_nat_ftp              1666  0 
nf_nat_amanda           1012  0 
ts_kmp                  1687  5 
nf_conntrack_amanda     2475  1 nf_nat_amanda
nf_conntrack_sane       3260  0 
nf_conntrack_tftp       3115  1 nf_nat_tftp
nf_conntrack_sip       20334  1 nf_nat_sip
nf_conntrack_proto_udplite     2812  0 
nf_conntrack_proto_sctp     6672  0 
nf_conntrack_pptp       5114  1 nf_nat_pptp
nf_conntrack_proto_gre     4831  1 nf_conntrack_pptp
nf_conntrack_netlink    17614  0 
nf_conntrack_netbios_ns     1075  0 
nf_conntrack_broadcast     1167  2 nf_conntrack_netbios_ns,nf_conntrack_snmp
nf_conntrack_irc        3666  1 nf_nat_irc
nf_conntrack_h323      45341  1 nf_nat_h323
nf_conntrack_ftp        5856  1 nf_nat_ftp
xt_TPROXY               4157  0 
nf_defrag_ipv6          6039  1 xt_TPROXY
ipv6                  271235  20 nf_defrag_ipv6,xt_TPROXY
ip6_tables             12481  1 xt_TPROXY
nf_tproxy_core          1144  1 xt_TPROXY
xt_tcpmss               1279  0 
xt_pkttype               898  0 
xt_physdev              1761  0 
xt_owner                1028  0 
xt_NFQUEUE              1900  0 
xt_NFLOG                 955  0 
nfnetlink_log           7976  1 xt_NFLOG
xt_multiport            1555  0 
xt_mark                 1013  0 
xt_mac                   918  0 
xt_limit                1560  0 
xt_length               1022  0 
xt_iprange              1395  0 
xt_helper               1177  0 
xt_hashlimit            7713  0 
xt_DSCP                 1771  0 
xt_dscp                 1451  0 
xt_dccp                 1971  0 
xt_conntrack            2794  0 
xt_connmark             1641  0 
xt_CLASSIFY              873  0 
xt_AUDIT                2772  0 
ipt_LOG                 6774  0 
xt_tcpudp               2065  0 
xt_state                1124  0 
iptable_nat             3727  0 
nf_nat                 16554  12 iptable_nat,nf_nat_amanda,nf_nat_ftp,nf_nat_h323,nf_nat_irc,nf_nat_proto_gre,nf_nat_pptp,nf_nat_sip,nf_nat_tftp,ipt_MASQUERADE,ipt_NETMAP,ipt_REDIRECT
nf_conntrack_ipv4      11719  3 nf_nat,iptable_nat
nf_defrag_ipv4          1307  2 nf_conntrack_ipv4,xt_TPROXY
nf_conntrack           71727  33 nf_conntrack_ipv4,nf_nat,iptable_nat,xt_state,xt_connmark,xt_conntrack,xt_helper,nf_conntrack_ftp,nf_conntrack_h323,nf_conntrack_irc,nf_conntrack_broadcast,nf_conntrack_netbios_ns,nf_conntrack_netlink,nf_conntrack_proto_gre,nf_conntrack_pptp,nf_conntrack_proto_sctp,nf_conntrack_proto_udplite,nf_conntrack_sip,nf_conntrack_tftp,nf_conntrack_sane,nf_conntrack_amanda,nf_nat_amanda,nf_nat_ftp,nf_nat_h323,nf_nat_irc,nf_nat_pptp,nf_nat_sip,nf_conntrack_snmp,nf_nat_snmp_basic,nf_nat_tftp,ipt_MASQUERADE,xt_connlimit,xt_CT
iptable_mangle          1433  0 
nfnetlink               4269  3 nfnetlink_log,nf_conntrack_netlink,ip_set
iptable_filter          1492  0 
ip_tables              11381  4 iptable_filter,iptable_mangle,iptable_nat,iptable_raw
x_tables               16750  49 ip_tables,iptable_filter,iptable_mangle,iptable_nat,xt_state,xt_tcpudp,ipt_LOG,xt_AUDIT,xt_CLASSIFY,xt_connmark,xt_conntrack,xt_dccp,xt_dscp,xt_DSCP,xt_hashlimit,xt_helper,xt_iprange,xt_length,xt_limit,xt_mac,xt_mark,xt_multiport,xt_NFLOG,xt_NFQUEUE,xt_owner,xt_physdev,xt_pkttype,xt_tcpmss,ip6_tables,xt_TPROXY,xt_set,ipt_ah,ipt_ecn,ipt_ECN,ipt_MASQUERADE,ipt_NETMAP,ipt_REDIRECT,ipt_REJECT,ipt_ULOG,xt_policy,xt_recent,xt_comment,iptable_raw,xt_addrtype,xt_realm,xt_connlimit,xt_time,xt_CT,xt_statistic
snd_bcm2835            12808  0 
snd_usb_audio          93242  0 
snd_usbmidi_lib        17812  1 snd_usb_audio
snd_hwdep               5730  1 snd_usb_audio
snd_seq_midi            4518  0 
snd_seq_midi_event      6453  1 snd_seq_midi
snd_rawmidi            20611  2 snd_seq_midi,snd_usbmidi_lib
snd_pcm                74834  2 snd_usb_audio,snd_bcm2835
snd_page_alloc          4951  1 snd_pcm
snd_seq                52536  2 snd_seq_midi_event,snd_seq_midi
snd_seq_device          6300  3 snd_seq,snd_rawmidi,snd_seq_midi
snd_timer              19698  2 snd_seq,snd_pcm
videobuf2_vmalloc       1965  0 
videobuf2_memops        2364  1 videobuf2_vmalloc
videobuf2_core         21366  0 
v4l2_common             9405  0 
snd                    52489  9 snd_timer,snd_seq_device,snd_seq,snd_pcm,snd_rawmidi,snd_hwdep,snd_usbmidi_lib,snd_usb_audio,snd_bcm2835
videodev               88790  1 v4l2_common

**Comment by ezequielgarcia** [comment]
Please note:
1. stk1160 support in RPI is from bad to broken.
2. rpi branch from stk1160 repo, appears to be broken as well. I had no time to fix it.

**Comment by ghost** [comment]
I understand. Indeed, thanks for your code. Have a nice day.
