### ISSUE TITLE
stk1160-raspberrypi: driver loaded but no image

### ISSUE THREAD

**Issue by pantonio** [piotr-e/Stk1160-raspberrypi#3]
Hi,

I want to capture image on Raspberry Pi with a stk1160 chip set device.

I had compiled the driver successfully. Then, I loaded the driver with success.

But then I tried vlc and mplayer to capture video and I get no success.

With VLC the messages were (I can see no video):
rawvideo decoder warning: invalid frame size (739446 < 829440)
rawvideo decoder warning: invalid frame size (748606 < 829440)
...

With mplayer the messages were (I can see an irregular video):
Frame too small! (735220<829440) Wrong format?
V:   0.0 212/212 ??% ??% ??,?% 0 0
...

Also, using "dd" I am getting data from device.
63861760 bytes (64 MB) copied, 3.14772 s, 20.3 MB/s

The dmesg has a lot of errors:
...
[ 1372.488118] URB packet 45, status -63 [Buffer error (overrun)].
[ 1372.504833] URB packet 0, status -63 [Buffer error (overrun)].
[ 1372.504876] URB packet 52, status -63 [Buffer error (overrun)].
...

I will appreciate any help.

Thank you in advanced, Pedro.

**Comment by piotr-e** [comment]
Can you make it and show result? 
#uname -a

**Comment by pantonio** [comment]
I cannot do it rigth now, but I compiled the kernel from raspberry git 3.2.27 branch with default .config.

The kernel version is 3.2.27+.

As soon as possible I post the uname -a result.

**Comment by piotr-e** [comment]
So, driver doesn't work properly for kernel 3.2. Only Raspbian 3.6.y is now corrected, but driver for kernel 3.6 doesn't exist yet.  
I'm sorry.

**Comment by raykov** [comment]
hello @pantonio. Can you send me your version of compiled module stk1160.ko to ****.*** @ ***.***? 

i will try it on my rpi.

thanks

**Comment by pantonio** [comment]
Here it is the "uname -a" result:

Linux raspberrypi 3.2.27+ #1 PREEMPT Fri Mar 15 10:00:04 WET 2013 armv6l GNU/Linux

**Comment by piotr-e** [comment]
You can update system and check again.

See issue: I can't make it work
